name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git fetch --tags

      - name: Check for tags and set version
        id: get_version
        run: |
          if git describe --tags > /dev/null 2>&1; then
            VERSION=$(git describe --tags)
          else
            VERSION="v0.0.0"
          fi
          echo "VERSION=$VERSION" > VERSION
          echo "::set-output name=version::$VERSION"

      - name: Display version
        run: cat VERSION

      # Add other steps here that depend on the VERSION file or variable
