name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Attempt to log in to Docker, but ignore errors
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: true

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-image:latest .

      # Optionally push the Docker image if login was successful
      - name: Push Docker image
        if: success() && !failure()
        run: |
          docker push my-image:latest
